import { FirebaseApp, initializeApp } from "firebase/app";
// Using zod for runtime validation
import { z } from "zod";

// NOTE: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

let firebaseApp: FirebaseApp | null = null;

// NOTE: schema generated by AI
const FirebaseConfigSchema = z.object({
  apiKey: z.string().startsWith("AIza"),
  authDomain: z.string().includes(".firebaseapp.com"),
  projectId: z.string().min(1),
  storageBucket: z.string().endsWith(".firebasestorage.app"),
  messagingSenderId: z.string().min(1),
  appId: z.string().startsWith("1:"),
  measurementId: z.string().startsWith("G-").optional(),
});

// NOTE: get firebase config from environment variables
const firebaseConfig = {
  apiKey: process.env["NEXT_PUBLIC_FIREBASE_API_KEY"],
  authDomain: process.env["NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"],
  projectId: process.env["NEXT_PUBLIC_FIREBASE_PROJECT_ID"],
  storageBucket: process.env["NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"],
  messagingSenderId: process.env["NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"],
  appId: process.env["NEXT_PUBLIC_FIREBASE_APP_ID"],
  measurementId: process.env["NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID"],
};

try {
  FirebaseConfigSchema.parse(firebaseConfig);
  firebaseApp = initializeApp(firebaseConfig, "evtree");
} catch (error) {
  console.warn(
    `[EVTree] Firebase failed to initialize: ${error}. Continuing without Firebase.`,
  );
}

export { firebaseApp };
