import { FirebaseApp, initializeApp } from "firebase/app";
// Using zod for runtime validation
import { z } from "zod";

// NOTE: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

let firebaseApp: FirebaseApp | null = null;

// NOTE: schema generated by AI
const FirebaseConfigSchema = z.object({
  apiKey: z.string().startsWith("AIza"),
  authDomain: z.string().includes(".firebaseapp.com"),
  projectId: z.string().min(1),
  storageBucket: z.string().endsWith(".firebasestorage.app"),
  messagingSenderId: z.string().min(1),
  appId: z.string().startsWith("1:"),
  measurementId: z.string().startsWith("G-").optional(),
});

// NOTE: get firebase config from Firebase console
const firebaseConfig = {
  apiKey: "AIzaSyCpQAoZEZufrRsOxev2TNcP_A_D0dwbasM",
  authDomain: "evtree-1.firebaseapp.com",
  projectId: "evtree-1",
  storageBucket: "evtree-1.firebasestorage.app",
  messagingSenderId: "121004750347",
  appId: "1:121004750347:web:363a33cb86ebe5d51d790e",
  measurementId: "G-QDEWK2W36Z",
};

try {
  FirebaseConfigSchema.parse(firebaseConfig);
  firebaseApp = initializeApp(firebaseConfig, "evtree");
} catch (error) {
  console.warn(
    `[EVTree] Firebase failed to initialize: ${error}. Continuing without Firebase.`,
  );
}

export { firebaseApp };
