/*
NOTE: Code here was initially generated by NextJS
*/

import { FlatCompat } from "@eslint/eslintrc";
import tailwind from "eslint-plugin-tailwindcss";
import { dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    ignores: [".next/**"],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  ...tailwind.configs["flat/recommended"],
  {
    // NOTE: added by gregdingle
    rules: {
      "no-console": ["warn", { allow: ["warn", "error"] }],
    },
    settings: {
      tailwindcss: {
        // Disable config file requirement for Tailwind v4
        config: false,
        whitelist: [
          // ReactFlow classes
          "nopan",
          "nodrag",
          // EVTree classes
          "evtree",
        ],
      },
    },
  },
];

export default eslintConfig;
